### ISSUE TITLE
anagram failing to compile on Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-llvm-test-suite#57]
Apparently the tolower and isalpha macros involve a function call that returns an unchecked pointer.  Here is an example error:
```
mnt/d/autobahn1/llvm-test-suite/MultiSource/Benchmarks/Ptrdist/anagram/anagram.c:300:17: error: cannot use a return with an unchecked type in a checked scope or function
            if (isalpha(ch)) cLetters++;
                ^
/usr/include/ctype.h:198:21: note: expanded from macro 'isalpha'
# define isalpha(c)     __isctype((c), _ISalpha)
                        ^
/usr/include/ctype.h:89:6: note: expanded from macro '__isctype'
  ((*__ctype_b_loc ())[(int) (c)] & (unsigned short int) type)
     ^
```

**Comment by dtarditi** [comment]
@lenary  explained to me that it will be complicated to add the bounds annotation needed for the value returned by `__ctype_b_loc`.    It requires return_value, which we have not implemented yet, and new functionality for describing bounds on `array_ptr` pointed to by another `ptr`.   The `array_ptr` has bounds whose lower/upper bounds are constant offsets from itself.    We already knew that we could handle pointers to array_ptrs with constant counts.  We can generalize this to handle `array_ptrs` with bounds given by constant offsets to themselves..   

@lenary, this is causing out LNT nightly tests to fail on Linux.  Because it will be a while before the new functionality is implemented so that this failure can be fixed, could you update anagram so that it doesn't fail on Linux?  Otherwise there is a risk of additional regressions happening on the LNT nightly tests that we miss.

**Comment by lenary** [comment]
Sure, I'll do that later today, adding an _Unchecked { } block around any `isletter()` calls and similar.

**Comment by lenary** [comment]
So, on further inspection, that function is a locale thing, which is why they don't want to use global variables.

Changes incoming for isletter etc.
