### PR TITLE
Fix for unchecked isalpha(int) bug in anagram.c

### LINKED ISSUE #57: anagram failing to compile on Linux Ubuntu 14.04
Apparently the tolower and isalpha macros involve a function call that returns an unchecked pointer.  Here is an example error:
```
mnt/d/autobahn1/llvm-test-suite/MultiSource/Benchmarks/Ptrdist/anagram/anagram.c:300:17: error: cannot use a return with an unchecked type in a checked scope or function
            if (isalpha(ch)) cLetters++;
                ^
/usr/include/ctype.h:198:21: note: expanded from macro 'isalpha'
# define isalpha(c)     __isctype((c), _ISalpha)
                        ^
/usr/include/ctype.h:89:6: note: expanded from macro '__isctype'
  ((*__ctype_b_loc ())[(int) (c)] & (unsigned short int) type)
     ^
```

### PR DESCRIPTION
**Pull request by lenary**
Rather than introducing unchecked blocks, I thought it easier just to make 1-line unchecked wrappers, and then use `#define`s to make sure all calls to `isalpha` or `toletter` used the wrappers.

This keeps diffs small, and allows us to remove the wrappers later when we extend the specification to deal with bounds on inner checked array pointers.

Fixes #57

### CODE REVIEW

**Review by dtarditi — COMMENTED** [review]
It is undefined behavior  in C to #define an existing macro to a new definition.    I think an easier fix is to #undef the isalpha/tolower macros instead.   When C library implementers provide function-like macros for standard functions, they must also define the functions too.

**Comment by lenary** [comment]
Commit using `#undef`. I put them inside an `#ifdef` but not sure that's necessary.

**Review by dtarditi — APPROVED** [review]
It is legal to #undef a symbol that isn't undefined; it has no effect.  In any case, I think it's fine to have them under an ifdef for now.

**Comment by lenary** [comment]
I assume you mean "that isn't defined". I'll go back and remove the ifdef and merge this right now.

**Comment by dtarditi** [comment]
Yes.
